/**
 * Testimonials — Appendix A.14. All rated 5 stars on the legacy site.
 *
 * These are third-party quotes: NEVER edit the text. Only the §10 corrections
 * of the spec were applied (T02 "challenging", T22/T32 "Liaison", T11/T29 "Celorico").
 *
 * TODO(cliente): T14, T40 mention "Lighthouse" (former brand) — keep verbatim (spec §11.1).
 * TODO(cliente): T45 contains "o mercado de mercado" in the original — likely a typo,
 *   not corrected without approval.
 * TODO(cliente): Italian/German pages reuse testimonials about English lessons (spec §11.8).
 */
import type { Testimonial } from "./types";

export const testimonials = [
  {
    id: "T01",
    name: "Affinity Portugal",
    role: "IT Consulting",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Mafalda-Inverno-1.png",
    text: "Adoramos a formação em inglês com a Karine! Mesmo online, as aulas são muito dinâmicas, com temas pertinentes e adaptados à atualidade.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T02",
    name: "Tara Goulet",
    role: "Empresária",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Tara-Goulet.jpg",
    text: "Karine's compassion and professionalism were exactly what I needed in a time when learning a language felt challenging.",
    lang: "en",
    rating: 5,
  },
  {
    id: "T03",
    name: "Tiago Soares",
    role: "Professor de Inglês, Português e Italiano",
    city: "Porto",
    country: "Portugal",
    photo: "2022/05/Tiago-Soares.png",
    text: "Mudar de aulas regulares para as aulas online pode ser bastante desafiador, mas a Karine tem me ajudado bastante! O seu profissionalismo e empenho merecem especial destaque!",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T04",
    name: "Natália Monteiro",
    role: "Professora de Inglês",
    city: "Olinda",
    country: "Brasil",
    photo: "2022/04/Natalia-Monteiro.jpg",
    text: "Eu já tinha experiência, mas ter o treinamento com Karine foi essencial para a preparação das aulas. Ela me passou dicas e muitas ferramentas para as aulas online.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T05",
    name: "Carolina Simões",
    role: "Corporate Talent Manager",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/05/Carolina-Simoes.jpg",
    text: "As aulas da Karine foram muito enriquecedoras. Ela sabe como conquistar o seu público e adequa cuidadosamente os materiais e conteúdos da aula ao contexto dos alunos.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T06",
    name: "Ana Miranda",
    role: "Training Manager",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Ana-Miranda-1.jpg",
    text: "Fiz uma aula experimental com o pensamento de que pouco ou nada falaria por não me sentir muito à vontade, mas em poucos segundos percebi que a Karine era a pessoa certa para eu voltar a desenvolver o meu inglês.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T07",
    name: "Helena Cardoso",
    role: "Produção Audiovisual",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Helena-Cardodo-1.jpg",
    text: "As temáticas abordadas são situações reais e usadas em contexto de trabalho o que ajuda no dia-a-dia. Noto uma diferença enorme passados alguns meses, já penso em inglês sem precisar de traduzir.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T08",
    name: "Ana Miranda",
    role: "Training Manager",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Ana-Miranda-1.jpg",
    text: "Extremamente empática, dinâmica e preocupada com a assimilação dos conteúdos, faz com que as aulas sejam sempre diferentes, interativas e muito interessantes. Voltei a estudar inglês com gosto e agora sinto-me muito mais à vontade a utilizá-lo em contexto profissional.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T09",
    name: "Carolina Simões",
    role: "Corporate Talent Manager",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/05/Carolina-Simoes.jpg",
    text: 'De destacar a boa disposição da formadora e o gosto com que ensina inglês, tornando as aulas dinâmicas e interativas, mesmo em contexto de Zoom. Ajudou-me muito a desbloquear a barreira de "falar inglês em público" e a adquirir novo vocabulário.',
    lang: "pt",
    rating: 5,
  },
  {
    id: "T10",
    name: "Mario Oliveira",
    role: "Unit Manager",
    city: "Lisboa",
    country: "Portugal",
    photo: "2023/07/WhatsApp-Image-2023-07-17-at-10.54.15.jpeg",
    text: "O formato personalizado e direcionado aos meus interesses (sobretudo profissionais) que as aulas têm e a informalidade e confiança com que são conduzidas têm sido fundamentais para a minha progressão.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T11",
    name: "Carolina Celorico",
    role: "Gestora de Recursos Humanos",
    city: "Setúbal",
    country: "Portugal",
    photo: "2023/07/WhatsApp-Image-2023-07-14-at-20.17.28.jpeg",
    text: "My teacher is incredibly patient and adept at explaining topics, often using examples from our daily lives. She also shares helpful tips.",
    lang: "en",
    rating: 5,
  },
  {
    id: "T12",
    name: "Eduardo Queiroz",
    role: "Analista Financeiro",
    city: "Recife",
    country: "Brasil",
    photo: "2023/07/WhatsApp-Image-2023-07-14-at-15.52.48.jpeg",
    text: "I already had listening and speaking skills, but I needed to acquire technical vocabulary and improve my grammar and Karine's classes were essential to improving my English skills and getting better job opportunities.",
    lang: "en",
    rating: 5,
  },
  {
    id: "T13",
    name: "Estrela Mestrinho",
    role: "Estudante",
    city: "Mullingar",
    country: "Irlanda",
    photo: "2022/05/Estrela-Mestrinho.jpg",
    text: "Eu amei a Karine como professora pois ela me deu a opção de fazer apenas conversação que no momento era o que eu mais necessitava. Em meio a várias conversas nossas sempre me aplicava a gramática que é como eu aprendo.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T14",
    name: "Tulio Aoki",
    role: "Programador",
    city: "Recife",
    country: "Brasil",
    photo: "2022/05/Tulio-Aoki.png",
    text: "A Lighthouse traz todas essas qualidades com toda a flexibilidade, preparação e a abordagem que melhor se encaixa em cada perfil. E o melhor: sempre há sorrisos na tela!",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T15",
    name: "Amanda Araujo",
    role: "Psicóloga",
    city: "Recife",
    country: "Brasil",
    photo: "2022/04/Amanda-Araujo-1.png",
    text: "Além da qualificação da professora, a identificação pessoal entra na minha lista de pré-requisitos para a aprendizagem da língua e compreendo em cada aula que esse processo pode ser prazeroso e fluido - com boas pitadas de sorrisos e leveza.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T16",
    name: "Margarida Fernandes",
    role: "Talent Manager",
    city: "Évora",
    country: "Portugal",
    photo: "2022/04/Margarida-Fernandes.jpg",
    text: "Inscrevi-me no curso de Inglês com o objetivo de melhorar a minha comunicação oral e tenho sentido que estou a evoluir bastante.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T17",
    name: "Tatiana Bertulino",
    role: "Psicóloga",
    city: "Recife",
    country: "Brasil",
    photo: "2022/04/Tatiana-Bertulino.png",
    text: "Karine consegue fazer com que as aulas sejam estimulantes, mantendo assim nosso interesse.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T18",
    name: "Rafael Paixão",
    role: "Engenheiro",
    city: "Paris",
    country: "França",
    photo: "2022/05/Rafael-Paixao.jpeg",
    text: "O conteúdo das aulas é diversificado e atual e as aulas te permitem praticar todas as competências linguísticas, seja listening, writing, reading e speaking.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T19",
    name: "Tara Goulet",
    role: "Empresária",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Tara-Goulet.jpg",
    text: "Karine is extremely adaptive. Her deep understanding of both English and Portuguese allows me to better understand and learn Portuguese.",
    lang: "en",
    rating: 5,
  },
  {
    id: "T20",
    name: "Luciana Almeida",
    role: "HR Assistant",
    city: "Porto",
    country: "Portugal",
    photo: "2024/03/Screenshot-2024-03-27-085225.png",
    text: "Karine's dedication and passion for teaching are truly inspiring, and I am immensely thankful for all the guidance and support she has provided me with during this time.",
    lang: "en",
    rating: 5,
  },
  {
    id: "T21",
    name: "Margarida Fernandes",
    role: "Talent Manager",
    city: "Évora",
    country: "Portugal",
    photo: "2022/04/Margarida-Fernandes.jpg",
    text: "Acima de tudo, praticamos muita conversação, o que para mim é o mais importante.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T22",
    name: "Lilian Amorim",
    role: "Medical Science Liaison",
    city: "Recife",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-21-085138.png",
    text: "O curso e as aulas me surpreenderam positivamente, é diferente de tudo o que eu já experimentei em cursos de inglês.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T23",
    name: "Roberto Dias",
    role: "Engenheiro",
    city: "Recife",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-21-084844.png",
    text: "É incrível a didática dos professores da Mundi e a competência de trazer para as aulas temas atuais, provocando discussões.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T24",
    name: "Auremir Santos",
    role: "Jogador de Futebol",
    city: "Chapecó",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-26-141355-1.png",
    text: "Karine tem me ajudado muito. Tenho conseguido manter a constância nas aulas devido a possibilidade de flexibilizar os horários ao longo da semana.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T25",
    name: "Tulio Aoki",
    role: "Programador",
    city: "Recife",
    country: "Brasil",
    photo: "2022/05/Tulio-Aoki.png",
    text: "A Mundi traz todas essas qualidades com toda a flexibilidade, preparação e a abordagem que melhor se encaixa em cada perfil. E o melhor: sempre há sorrisos na tela!",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T26",
    name: "Ana Miranda",
    role: "Training Manager",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Ana-Miranda-1.jpg",
    text: "Extremamente empática, dinâmica e preocupada com a assimilação dos conteúdos, faz com que as aulas sejam sempre diferentes, interativas e muito interessantes.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T27",
    name: "Helena Cardoso",
    role: "Produção Audiovisual",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Helena-Cardodo-1.jpg",
    text: "As temáticas abordadas são situações reais e usadas em contexto de trabalho o que ajuda no dia-a-dia. Noto uma diferença enorme passados alguns meses.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T28",
    name: "Carolina Simões",
    role: "Corporate Talent Manager",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/05/Carolina-Simoes.jpg",
    text: "De destacar a boa disposição da formadora, tornando as aulas dinâmicas e interativas, mesmo em contexto de Zoom.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T29",
    name: "Carolina Celorico",
    role: "Gestora de RH",
    city: "Setúbal",
    country: "Portugal",
    photo: "2023/07/WhatsApp-Image-2023-07-14-at-20.17.28.jpeg",
    text: "To enhance my learning experience, my teacher sends me engaging exercises and videos to reinforce what I have been learning. I truly value her efforts in this regard!",
    lang: "en",
    rating: 5,
  },
  {
    id: "T30",
    name: "Roberto Dias",
    role: "Engenheiro",
    city: "Recife",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-21-084844.png",
    text: 'Hoje, é bem claro pra mim que eu entro em "sala" duas vezes por semana pra falar inglês com um professor que vai conversar comigo e vai me dar feedbacks de gramática e pronúncia como se eu estivesse conversando com um amigo.',
    lang: "pt",
    rating: 5,
  },
  {
    id: "T31",
    name: "Margarida Fernandes",
    role: "Talent Manager",
    city: "Évora",
    country: "Portugal",
    photo: "2022/04/Margarida-Fernandes.jpg",
    text: "Falamos sobre vários temas da atualidade, temas profissionais e, acima de tudo, praticamos muita conversação, o que para mim é o mais importante.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T32",
    name: "Lilian Amorim",
    role: "Medical Science Liaison",
    city: "Recife",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-21-085138.png",
    text: "Karine proporciona um ambiente leve, estimulando a nossa fala com conversas sempre construtivas e com temas relevantes para o âmbito profissional, sempre pontuando melhorias e ajudando no desenvolvimento gramatical.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T33",
    name: "Luciana Almeida",
    role: "HR Assistant",
    city: "Porto",
    country: "Portugal",
    photo: "2024/03/Screenshot-2024-03-27-085225.png",
    text: "I would like to express my deepest gratitude for the magnificent work Karine has been doing in teaching me the English language.",
    lang: "en",
    rating: 5,
  },
  {
    id: "T34",
    name: "Auremir Santos",
    role: "Jogador de Futebol",
    city: "Chapecó",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-26-141355-1.png",
    text: "O que eu acho mais interessante nesse formato de estudar é a leveza com a qual temos as aulas, fazendo atividades de acordo com a minha necessidade e enfatizando aquilo que preciso evoluir.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T35",
    name: "Marcia Ferreira",
    role: "Empresária",
    city: "Lisboa",
    country: "Portugal",
    photo: "2022/04/Marcia-Ferreira.png",
    text: "A Karine, como é genuinamente altruísta, desenhou um plano adaptado às minhas necessidades que me fez perder o medo de falar inglês e ganhar confiança. E fez mais: fez com que tivesse prazer em falar inglês.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T36",
    name: "Roberto Dias",
    role: "Engenheiro",
    city: "Recife",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-21-084844.png",
    text: "Estava cansado do inglês baseado em regras gramaticais e queria algo mais focado em resultado, ou seja, que no contexto dos bate-papos das aulas a gramática e pronuncia fosse inserida.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T37",
    name: "Tulio Aoki",
    role: "Programador",
    city: "Recife",
    country: "Brasil",
    photo: "2022/05/Tulio-Aoki.png",
    text: "Trabalho com programação e é impossível não esbarrar com inglês. Mas saber essa língua é, além de necessário, recompensador - participar de processos seletivos em diversos países, ver filmes e séries sem legenda, e é claro, conversar com outras pessoas.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T38",
    name: "Elisa Araujo",
    role: "Professora de Inglês",
    city: "Jaboatão",
    country: "Brasil",
    photo: "2022/04/Elisa-Araujo-1-e1653224546455.jpeg",
    text: "Sempre empenhada, proativa e com um grande domínio de metodologias, sua dedicação ao trabalho foi de grande inspiração. Além de uma excelente profissional, possui uma enorme empatia e simplicidade.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T39",
    name: "Gabriela Kopinits",
    role: "Professora de Inglês, Jornalista e Escritora",
    city: "Caruaru",
    country: "Brasil",
    photo: "2022/04/Gabriela-Kopinits-1.jpg",
    text: "Uma escola sem fronteiras, adaptada às necessidades do aluno, com aulas personalizadas que respeitam o seu ritmo e autonomia. Tem sido, ao mesmo tempo, desafio e oportunidade de evolução para os professores nesta nova realidade.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T40",
    name: "Natália Monteiro",
    role: "Professora de Inglês",
    city: "Olinda",
    country: "Brasil",
    photo: "2022/04/Natalia-Monteiro.jpg",
    text: "Tive uma experiência maravilhosa com a Lighthouse quando comecei a ensinar inglês para crianças online (...) Foi uma grande experiência em que consegui desenvolver meu potencial e criatividade ao ensinar crianças.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T41",
    name: "Tiago Galdino",
    role: "Professor de Inglês",
    city: "Recife",
    country: "Brasil",
    photo: "2024/03/Tiago.jpeg",
    text: "Karine é uma das mais competentes, organizadas e prestativas profissionais com quem já tive o prazer de trabalhar.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T42",
    name: "Isa França",
    role: "Coordenadora de Educação Bilíngue",
    city: "Olinda",
    country: "Brasil",
    photo: "2022/05/Isa-Franca.jpg",
    text: "Conheci Karine em 2010. Na época éramos colegas e tive o prazer de aprender muito com ela, compartilhar conhecimento e de pensar na educação de maneira mais humana e inclusiva.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T43",
    name: "Robson Machado",
    role: "Professor de Inglês",
    city: "Recife",
    country: "Brasil",
    photo: "2022/04/Robson-Machado.jpg",
    text: "Karine é uma coordenadora excelente e teacher maravilhosa que busca trabalhar junto com os teachers buscando sempre o melhor para os alunos e para a escola.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T44",
    name: "Roberto Dias",
    role: "Engenheiro",
    city: "Recife",
    country: "Brasil",
    photo: "2024/03/Screenshot-2024-03-21-084844.png",
    text: "Conheci a Mundi em plena pandemia… como muitos, por recomendação de colegas de trabalho. Eu gostei de cara da abordagem dos professores! Um ensino de inglês contextualizado, focado, no meu caso, com o que eu estava exatamente precisando: falar inglês.",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T45",
    name: "Alex Rosetti e Livia Ret",
    role: "Gerente de Logística e Professora de Português",
    city: "São Paulo",
    country: "Brasil",
    photo: "2022/05/Livia-e-Alex.png",
    text: "Estudar inglês nos torna pessoas e profissionais melhores, pois o mercado de mercado está muito competitivo e exige outras línguas no currículo. Estudar online tem suas vantagens: o material é bastante lúdico com imagens, vídeos, jogos e a conversação acontece toda hora!",
    lang: "pt",
    rating: 5,
  },
  {
    id: "T46",
    name: "Robson Machado",
    role: "Professor de Inglês",
    city: "Recife",
    country: "Brasil",
    photo: "2022/04/Robson-Machado.jpg",
    text: "Karine é uma coordenadora excelente e teacher maravilhosa que busca trabalhar junto com os teachers buscando sempre o melhor para os alunos e para a escola. Profissional dedicada, responsável e que leva com seriedade as tarefas a ela designadas.",
    lang: "pt",
    rating: 5,
  },
] as const satisfies readonly Testimonial[];

export type TestimonialId = (typeof testimonials)[number]["id"];

const byId = new Map<string, Testimonial>(testimonials.map((t) => [t.id, t]));

export function getTestimonial(id: TestimonialId): Testimonial {
  return byId.get(id)!;
}

export function getTestimonials(ids: readonly TestimonialId[]): Testimonial[] {
  return ids.map(getTestimonial);
}

/** Label shown under the name: "Empresária, Lisboa, Portugal". */
export function testimonialCaption(testimonial: Testimonial) {
  return `${testimonial.role}, ${testimonial.city}, ${testimonial.country}`;
}
